FROM centos
COPY logstash/ /logstash
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum update -y && \
    yum install -y java && \
    yum install -y java-devel
# CMD /logstash/bin/logstash -f /logstash/config/logstash.conf & bash